# defaults: &defaults
#   adapter: postgresql
#   pool: 5
#   username: postgres
#   password: 12345678
#   host: us-community-jan2022.cug7shtp4znr.us-west-2.rds.amazonaws.com

# development:
#   database: form_builder
#   adapter: postgresql
#   username: postgres
#   password: 12345678
#   host: localhost

# test:
#   database: form_builder
#   <<: *defaults

# production:
#   database: form_builder
#   <<: *defaults
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: 1234
 
development:
  <<: *default
  database: form-builder

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>